### Retrieve all
GET {{host}}:{{port}}/api/shelter
Accept: application/json


### Create shelter
POST {{host}}:{{port}}/api/shelter
Accept: application/json
Content-Type: application/json

{
  "name": "test-connect-again",
  "province": "Galicia"
}

### Retrieve by id
GET {{host}}:{{port}}/api/shelter/1
Accept: application/json